---
name: Tracking issue
description: Use this template for tracking new features.
title: "[DATE]: [FEATURE NAME]"
labels: tracking issue, needs triage
assignees: octocat
---
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

